# Generated by Django 6.1.1 on 2026-09-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('UPI', 'UPI'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card')], default='COD', max_length=20),
        ),
    ]
